// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: tensorflow/core/framework/variable.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Protocol buffer representing a Variable.
public struct Tensorflow_VariableDef {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Name of the variable tensor.
  public var variableName: String {
    get {return _storage._variableName}
    set {_uniqueStorage()._variableName = newValue}
  }

  /// Name of the tensor holding the variable's initial value.
  public var initialValueName: String {
    get {return _storage._initialValueName}
    set {_uniqueStorage()._initialValueName = newValue}
  }

  /// Name of the initializer op.
  public var initializerName: String {
    get {return _storage._initializerName}
    set {_uniqueStorage()._initializerName = newValue}
  }

  /// Name of the snapshot tensor.
  public var snapshotName: String {
    get {return _storage._snapshotName}
    set {_uniqueStorage()._snapshotName = newValue}
  }

  /// Support for saving variables as slices of a larger variable.
  public var saveSliceInfoDef: Tensorflow_SaveSliceInfoDef {
    get {return _storage._saveSliceInfoDef ?? Tensorflow_SaveSliceInfoDef()}
    set {_uniqueStorage()._saveSliceInfoDef = newValue}
  }
  /// Returns true if `saveSliceInfoDef` has been explicitly set.
  public var hasSaveSliceInfoDef: Bool {return _storage._saveSliceInfoDef != nil}
  /// Clears the value of `saveSliceInfoDef`. Subsequent reads from it will return its default value.
  public mutating func clearSaveSliceInfoDef() {_uniqueStorage()._saveSliceInfoDef = nil}

  /// Whether to represent this as a ResourceVariable.
  public var isResource: Bool {
    get {return _storage._isResource}
    set {_uniqueStorage()._isResource = newValue}
  }

  /// Whether this variable should be trained.
  public var trainable: Bool {
    get {return _storage._trainable}
    set {_uniqueStorage()._trainable = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Tensorflow_SaveSliceInfoDef {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Name of the full variable of which this is a slice.
  public var fullName: String = String()

  /// Shape of the full variable.
  public var fullShape: [Int64] = []

  /// Offset of this variable into the full variable.
  public var varOffset: [Int64] = []

  /// Shape of this variable.
  public var varShape: [Int64] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "tensorflow"

extension Tensorflow_VariableDef: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VariableDef"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "variable_name"),
    6: .standard(proto: "initial_value_name"),
    2: .standard(proto: "initializer_name"),
    3: .standard(proto: "snapshot_name"),
    4: .standard(proto: "save_slice_info_def"),
    5: .standard(proto: "is_resource"),
    7: .same(proto: "trainable"),
  ]

  fileprivate class _StorageClass {
    var _variableName: String = String()
    var _initialValueName: String = String()
    var _initializerName: String = String()
    var _snapshotName: String = String()
    var _saveSliceInfoDef: Tensorflow_SaveSliceInfoDef? = nil
    var _isResource: Bool = false
    var _trainable: Bool = false

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _variableName = source._variableName
      _initialValueName = source._initialValueName
      _initializerName = source._initializerName
      _snapshotName = source._snapshotName
      _saveSliceInfoDef = source._saveSliceInfoDef
      _isResource = source._isResource
      _trainable = source._trainable
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularStringField(value: &_storage._variableName)
        case 2: try decoder.decodeSingularStringField(value: &_storage._initializerName)
        case 3: try decoder.decodeSingularStringField(value: &_storage._snapshotName)
        case 4: try decoder.decodeSingularMessageField(value: &_storage._saveSliceInfoDef)
        case 5: try decoder.decodeSingularBoolField(value: &_storage._isResource)
        case 6: try decoder.decodeSingularStringField(value: &_storage._initialValueName)
        case 7: try decoder.decodeSingularBoolField(value: &_storage._trainable)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._variableName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._variableName, fieldNumber: 1)
      }
      if !_storage._initializerName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._initializerName, fieldNumber: 2)
      }
      if !_storage._snapshotName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._snapshotName, fieldNumber: 3)
      }
      if let v = _storage._saveSliceInfoDef {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }
      if _storage._isResource != false {
        try visitor.visitSingularBoolField(value: _storage._isResource, fieldNumber: 5)
      }
      if !_storage._initialValueName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._initialValueName, fieldNumber: 6)
      }
      if _storage._trainable != false {
        try visitor.visitSingularBoolField(value: _storage._trainable, fieldNumber: 7)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Tensorflow_VariableDef, rhs: Tensorflow_VariableDef) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._variableName != rhs_storage._variableName {return false}
        if _storage._initialValueName != rhs_storage._initialValueName {return false}
        if _storage._initializerName != rhs_storage._initializerName {return false}
        if _storage._snapshotName != rhs_storage._snapshotName {return false}
        if _storage._saveSliceInfoDef != rhs_storage._saveSliceInfoDef {return false}
        if _storage._isResource != rhs_storage._isResource {return false}
        if _storage._trainable != rhs_storage._trainable {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Tensorflow_SaveSliceInfoDef: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SaveSliceInfoDef"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "full_name"),
    2: .standard(proto: "full_shape"),
    3: .standard(proto: "var_offset"),
    4: .standard(proto: "var_shape"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.fullName)
      case 2: try decoder.decodeRepeatedInt64Field(value: &self.fullShape)
      case 3: try decoder.decodeRepeatedInt64Field(value: &self.varOffset)
      case 4: try decoder.decodeRepeatedInt64Field(value: &self.varShape)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fullName.isEmpty {
      try visitor.visitSingularStringField(value: self.fullName, fieldNumber: 1)
    }
    if !self.fullShape.isEmpty {
      try visitor.visitPackedInt64Field(value: self.fullShape, fieldNumber: 2)
    }
    if !self.varOffset.isEmpty {
      try visitor.visitPackedInt64Field(value: self.varOffset, fieldNumber: 3)
    }
    if !self.varShape.isEmpty {
      try visitor.visitPackedInt64Field(value: self.varShape, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Tensorflow_SaveSliceInfoDef, rhs: Tensorflow_SaveSliceInfoDef) -> Bool {
    if lhs.fullName != rhs.fullName {return false}
    if lhs.fullShape != rhs.fullShape {return false}
    if lhs.varOffset != rhs.varOffset {return false}
    if lhs.varShape != rhs.varShape {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
