// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: tensorflow/python/training/checkpoint_state.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Protocol buffer representing the checkpoint state.
public struct Tensorflow_CheckpointState {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Path to the most-recent model checkpoint.
  public var modelCheckpointPath: String = String()

  /// Paths to all not-yet-deleted model checkpoints, sorted from oldest to
  /// newest.
  /// Note that the value of model_checkpoint_path should be the last item in
  /// this list.
  public var allModelCheckpointPaths: [String] = []

  /// Unix timestamps corresponding to all_model_checkpoint_paths, indicating
  /// when each checkpoint was created.
  public var allModelCheckpointTimestamps: [Double] = []

  /// Unix timestamp indicating the creation time for the last preserved
  /// checkpoint.
  public var lastPreservedTimestamp: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "tensorflow"

extension Tensorflow_CheckpointState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CheckpointState"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "model_checkpoint_path"),
    2: .standard(proto: "all_model_checkpoint_paths"),
    3: .standard(proto: "all_model_checkpoint_timestamps"),
    4: .standard(proto: "last_preserved_timestamp"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.modelCheckpointPath)
      case 2: try decoder.decodeRepeatedStringField(value: &self.allModelCheckpointPaths)
      case 3: try decoder.decodeRepeatedDoubleField(value: &self.allModelCheckpointTimestamps)
      case 4: try decoder.decodeSingularDoubleField(value: &self.lastPreservedTimestamp)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.modelCheckpointPath.isEmpty {
      try visitor.visitSingularStringField(value: self.modelCheckpointPath, fieldNumber: 1)
    }
    if !self.allModelCheckpointPaths.isEmpty {
      try visitor.visitRepeatedStringField(value: self.allModelCheckpointPaths, fieldNumber: 2)
    }
    if !self.allModelCheckpointTimestamps.isEmpty {
      try visitor.visitPackedDoubleField(value: self.allModelCheckpointTimestamps, fieldNumber: 3)
    }
    if self.lastPreservedTimestamp != 0 {
      try visitor.visitSingularDoubleField(value: self.lastPreservedTimestamp, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Tensorflow_CheckpointState, rhs: Tensorflow_CheckpointState) -> Bool {
    if lhs.modelCheckpointPath != rhs.modelCheckpointPath {return false}
    if lhs.allModelCheckpointPaths != rhs.allModelCheckpointPaths {return false}
    if lhs.allModelCheckpointTimestamps != rhs.allModelCheckpointTimestamps {return false}
    if lhs.lastPreservedTimestamp != rhs.lastPreservedTimestamp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
